name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm test

      - name: Publish to npm
        run: |
          npm install -g npm@latest
          npm publish --provenance --access public

      - name: Publish to GitHub Packages
        run: |
          npm config set registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          jq '.name = "@sudoeren/eckra" | .publishConfig = { "registry": "https://npm.pkg.github.com" }' package.json > package-gh.json
          mv package.json package.bak
          mv package-gh.json package.json
          npm publish
          mv package.bak package.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
